POST http://localhost:8000/bands/
Content-Type: application/json

{
    "name":"eminem",
    "genre":"Hip-Hop",
    "album":[
        {"title":"Master of reality","release_date":"1997-01-01"}]
}



###
GET http://localhost:8000/bands/
